name: 'Payara Cloud CLI Action'
description: 'Deploy an app to Payara Cloud using Payara Cloud CLI (PCL)'
inputs:
  token:
    description: 'token obtained from `pcl login --print-token` and stored in secrets'
    required: true
  cloud_subscription_id:
    description: 'The Payara Cloud subscription ID'
    required: true
  namespace:
    description: 'The namespace under which the app is deployed'
    required: true
  app_name:
    description: 'The name of the app to deploy'
    required: true
  artifact_location:
    description: 'The location of the artifact (WAR) to deploy'
    required: true
  pcl_version:
    description: 'Version of PCL to download'
    required: false
    default: '1.1.0'
runs:
  using: 'node12'
  main: 'dist/index.js'
